server:
  port: 8080

app:
  title: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"
  url: "@project.url@"
  developer:
    name: "@project.developers[0].name@"
    url: ""
    email: "@project.developers[0].email@"

spring:
  application.name: "@project.name@"

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      "[hibernate.format_sql]": "true"

  sql:
    init:
      mode: always
      schema-locations: file:schema.sql

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
